### ISSUE TITLE
this a hoax?

### ISSUE THREAD

**Issue by wonkytonky** [cshrem/Bitcoin-XYZ#12]

**Comment by lichtamberg** [comment]
I think you went the wrong way, hoaxchain is there: https://hoaxchain.com/index1.html

nack.

@cshrem this can be closed.

**Comment by MrHash** [comment]
This is a place for technical discussion only @wonkytonky. Please take your question to the ICQ channel and stop trolling. kthx

**Comment by desantis** [comment]
I'm not sure what this is anymore lol

**Comment by cshrem** [comment]
NACK
